version: "3.8"
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: maple
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db # 호스트 ./data/mongo → 컨테이너 /data/db

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin # 웹 로그인 계정
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"

  auth:
    build: ./auth-server
    env_file:
      - ./auth-server/.env
    depends_on:
      - mongodb
    ports: ["3001:3000"]
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:root@mongodb:27017/maple?authSource=admin

  event:
    build: ./event-server
    env_file:
      - ./event-server/.env
    depends_on:
      - mongodb
    ports: ["3002:3000"]
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:root@mongodb:27017/maple?authSource=admin

  gateway:
    build: ./gateway-server
    env_file:
      - ./gateway-server/.env
    depends_on:
      - mongodb
    ports: ["3003:3000"]
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:root@mongodb:27017/maple?authSource=admin

networks:
  default:
    name: msa-network
